name    'ghoneycutt-vim'
version '2.7.0'
source 'git://github.com/ghoneycutt/puppet-module-vim.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage everyone\'s favorite editor, Vim.'
description 'Manage Vim'
project_page 'https://github.com/ghoneycutt/puppet-module-vim'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
